export interface EquippedItem {
  serial: number;
  graphic: number;
  name: string;
}

export interface Player {
  get coldResistance(): Promise<number>;
  get damageIncrease(): Promise<number>;
  get damageMax(): Promise<number>;
  get damageMin(): Promise<number>;
  get deathScreenTimer(): Promise<number>;
  get defenseChanceIncrease(): Promise<number>;
  get dexterity(): Promise<number>;
  get dexterityIncrease(): Promise<number>;
  get energyResistance(): Promise<number>;
  get enhancePotions(): Promise<number>;
  get fasterCasting(): Promise<number>;
  get fasterCastRecovery(): Promise<number>;
  get fireResistance(): Promise<number>;
  get followers(): Promise<number>;
  get followersMax(): Promise<number>;
  get gold(): Promise<number>;
  get hitChanceIncrease(): Promise<number>;
  get hitPointsIncrease(): Promise<number>;
  get hitPointsRegeneration(): Promise<number>;
  get intelligence(): Promise<number>;
  get intelligenceIncrease(): Promise<number>;
  get lowerManaCost(): Promise<number>;
  get lowerReagentCost(): Promise<number>;
  get luck(): Promise<number>;
  get manaIncrease(): Promise<number>;
  get manaRegeneration(): Promise<number>;
  get maxColdResistence(): Promise<number>;
  get maxDefenseChanceIncrease(): Promise<number>;
  get maxEnergyResistence(): Promise<number>;
  get maxFireResistence(): Promise<number>;
  get maxHitPointsIncrease(): Promise<number>;
  get maxManaIncrease(): Promise<number>;
  get maxPhysicResistence(): Promise<number>;
  get maxPoisonResistence(): Promise<number>;
  get maxStaminaIncrease(): Promise<number>;
  get physicalResistance(): Promise<number>;
  get poisonResistance(): Promise<number>;
  get reflectPhysicalDamage(): Promise<number>;
  get spellDamageIncrease(): Promise<number>;
  get staminaIncrease(): Promise<number>;
  get staminaRegeneration(): Promise<number>;
  get statsCap(): Promise<number>;
  get strength(): Promise<number>;
  get strengthIncrease(): Promise<number>;
  get swingSpeedIncrease(): Promise<number>;
  get tithingPoints(): Promise<number>;
  get weight(): Promise<number>;
  get weightMax(): Promise<number>;
  get isPoisoned(): Promise<number>;
  get isYellowHits(): Promise<number>;
  get hits(): Promise<number>;
  get hitsMax(): Promise<number>;
  get mana(): Promise<number>;
  get manaMax(): Promise<number>;
  get stamina(): Promise<number>;
  get staminaMax(): Promise<number>;
  get name(): Promise<string>;
  get hunger(): Promise<number>;
  get shortTermMurders(): Promise<number>;
  get longTermMurders(): Promise<number>;
  get equippedItems(): Promise<{
    shirt?: EquippedItem;
    pants?: EquippedItem;
    shoes?: EquippedItem;
    legs?: EquippedItem;
    torso?: EquippedItem;
    ring?: EquippedItem;
    talisman?: EquippedItem;
    bracelet?: EquippedItem;
    face?: EquippedItem;
    arms?: EquippedItem;
    gloves?: EquippedItem;
    skirt?: EquippedItem;
    tunic?: EquippedItem;
    robe?: EquippedItem;
    necklace?: EquippedItem;
    hair?: EquippedItem;
    waist?: EquippedItem;
    beard?: EquippedItem;
    earrings?: EquippedItem;
    oneHanded?: EquippedItem;
    helmet?: EquippedItem;
    twoHanded?: EquippedItem;
    cloak?: EquippedItem;
    mount?: EquippedItem;
  }>;
}
